"""baseline schema portable (phase 1 fondation postgres)

Revision ID: adc3e4b5c1bb
Revises: 
Create Date: 2026-08-28 12:08:00.636073

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'adc3e4b5c1bb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("result IN ('allowed', 'denied')", name='ck_access_audit_result'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_access_audit_project_time', 'access_audit', ['project_id', 'occurred_at'], unique=False)
    op.create_table('app_setting',
    sa.Column('key', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('generation_job',
    sa.Column('id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('case_ids', sa.Text(), server_default='[]', nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generation_job_status', 'generation_job', ['status'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('connector_type', sa.Text(), server_default='odoo', nullable=False),
    sa.Column('base_url', sa.Text(), server_default='', nullable=False),
    sa.Column('database', sa.Text(), server_default='', nullable=False),
    sa.Column('username', sa.Text(), server_default='', nullable=False),
    sa.Column('password', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_at', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_by', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('default_access', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('uq_project_name', 'project', ['name'], unique=True, sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.create_table('project_access',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('no_access', 'lecture_seule', 'testeur', 'dev', 'admin')", name='ck_project_access_role'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("role IN ('lecture_seule', 'testeur', 'dev', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_user_username'),
    sqlite_autoincrement=True
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_user_group_name'),
    sqlite_autoincrement=True
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_at', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_by', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_module_project', 'module', ['project_id'], unique=False)
    op.create_index('uq_module_project_name', 'module', ['project_id', 'name'], unique=True, sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.create_table('project_group_access',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('', 'no_access', 'lecture_seule', 'testeur', 'dev', 'admin')", name='ck_project_group_access_role'),
    sa.ForeignKeyConstraint(['group_id'], ['user_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'group_id')
    )
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('lecture_seule', 'testeur', 'dev', 'admin')", name='ck_project_member_role'),
    sa.CheckConstraint("status IN ('active', 'suspended', 'removed')", name='ck_project_member_status'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index('idx_project_member_user', 'project_member', ['user_id', 'status'], unique=False)
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('refs', sa.Text(), server_default='', nullable=False),
    sa.Column('selection_mode', sa.Text(), server_default='frozen', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('launched_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mode', sa.Text(), server_default='automatique', nullable=False),
    sa.CheckConstraint("mode IN ('manuelle', 'automatique')", name='ck_test_run_mode'),
    sa.CheckConstraint("selection_mode IN ('all', 'frozen')", name='ck_test_run_selection_mode'),
    sa.CheckConstraint("status IN ('draft', 'running', 'completed')", name='ck_test_run_status'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_run_project', 'test_run', ['project_id'], unique=False)
    op.create_table('user_group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_index('idx_user_group_member_user', 'user_group_member', ['user_id'], unique=False)
    op.create_table('case_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('spec_content', sa.Text(), server_default='', nullable=False),
    sa.Column('spec_hash', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_enveloppe', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_by', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['case_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_case_group_parent', 'case_group', ['parent_group_id'], unique=False)
    op.create_index('idx_group_module', 'case_group', ['module_id'], unique=False)
    op.create_index('uq_group_module_title', 'case_group', ['module_id', 'title'], unique=True, sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.create_table('test_case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('feature_slug', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('origin', sa.Text(), server_default='ia_generated', nullable=False),
    sa.Column('type', sa.Text(), server_default='fonctionnel', nullable=False),
    sa.Column('etat', sa.Text(), server_default='new', nullable=False),
    sa.Column('priority', sa.Text(), server_default='medium', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('refs', sa.Text(), server_default='', nullable=False),
    sa.Column('estimate', sa.Text(), server_default='', nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('last_execution_status', sa.Text(), nullable=True),
    sa.Column('last_functional_status', sa.Text(), nullable=True),
    sa.Column('last_executed_at', sa.Text(), nullable=True),
    sa.Column('last_statut_manuel', sa.Text(), server_default='', nullable=False),
    sa.Column('last_result_mode', sa.Text(), server_default='', nullable=False),
    sa.Column('last_result_at', sa.Text(), server_default='', nullable=False),
    sa.Column('author', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_at', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_by', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("last_execution_status IN ('success', 'technical_error', 'not_executed')", name='ck_test_case_last_execution_status'),
    sa.CheckConstraint("last_functional_status IN ('conforme', 'non_conforme', 'indetermine', 'not_evaluated', 'donnee_invalide')", name='ck_test_case_last_functional_status'),
    sa.CheckConstraint("origin IN ('ia_generated', 'manual_converted')", name='ck_test_case_origin'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='ck_test_case_priority'),
    sa.ForeignKeyConstraint(['group_id'], ['case_group.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_case_group', 'test_case', ['group_id'], unique=False)
    op.create_index('idx_case_module', 'test_case', ['module_id'], unique=False)
    op.create_index('uq_case_feature_slug', 'test_case', ['feature_slug'], unique=True, sqlite_where=sa.text("feature_slug != '' AND deleted_at = ''"), postgresql_where=sa.text("feature_slug != '' AND deleted_at = ''"))
    op.create_index('uq_case_group_title', 'test_case', ['group_id', 'title'], unique=True, sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.create_table('run_case_assignment',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Text(), server_default='', nullable=False),
    sa.Column('assigned_by', sa.Text(), server_default='', nullable=False),
    sa.Column('assigned_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'case_id')
    )
    op.create_table('test_case_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('spec_content', sa.Text(), server_default='', nullable=False),
    sa.Column('spec_hash', sa.Text(), server_default='', nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('preconditions', sa.Text(), server_default='', nullable=False),
    sa.Column('test_steps', sa.Text(), server_default='', nullable=False),
    sa.Column('expected_result', sa.Text(), server_default='', nullable=False),
    sa.Column('feature_content', sa.Text(), server_default='', nullable=False),
    sa.Column('steps_content', sa.Text(), server_default='', nullable=False),
    sa.Column('feature_path', sa.Text(), server_default='', nullable=False),
    sa.Column('steps_path', sa.Text(), server_default='', nullable=False),
    sa.Column('change_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_version_case', 'test_case_version', ['test_case_id'], unique=False)
    op.create_table('test_run_case',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'case_id')
    )
    op.create_index('idx_runcase_run', 'test_run_case', ['run_id'], unique=False)
    op.create_table('execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('execution_status', sa.Text(), server_default='not_executed', nullable=False),
    sa.Column('functional_status', sa.Text(), server_default='not_evaluated', nullable=False),
    sa.Column('scenarios_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scenarios_passed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scenarios_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('iterations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('field_fallbacks', sa.Text(), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('trigger', sa.Text(), server_default='first_run', nullable=False),
    sa.Column('target_url', sa.Text(), server_default='', nullable=False),
    sa.Column('target_database', sa.Text(), server_default='', nullable=False),
    sa.Column('target_username', sa.Text(), server_default='', nullable=False),
    sa.Column('artifacts_path', sa.Text(), server_default='', nullable=False),
    sa.Column('triggered_by', sa.Text(), server_default='', nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("execution_status IN ('success', 'technical_error', 'not_executed')", name='ck_execution_execution_status'),
    sa.CheckConstraint("functional_status IN ('conforme', 'non_conforme', 'indetermine', 'not_evaluated', 'donnee_invalide')", name='ck_execution_functional_status'),
    sa.CheckConstraint("trigger IN ('first_run', 'rerun')", name='ck_execution_trigger'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['test_case_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_execution_case', 'execution', ['test_case_id'], unique=False)
    op.create_index('idx_execution_run', 'execution', ['run_id'], unique=False)
    op.create_table('review_decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.Text(), server_default='', nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=False),
    sa.Column('repair_budget', sa.Integer(), server_default='2', nullable=False),
    sa.Column('decided_at', sa.Text(), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name='ck_review_decision_decision'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['test_case_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_review_version', 'review_decision', ['version_id'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_month', sa.Text(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Text(), server_default='', nullable=False),
    sa.Column('model', sa.Text(), server_default='', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('source', sa.Text(), server_default='estimated', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("source IN ('estimated', 'anthropic_api')", name='ck_cost_ledger_source'),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_cost_case', 'cost_ledger', ['test_case_id'], unique=False)
    op.create_index('idx_cost_period', 'cost_ledger', ['period_month'], unique=False)
    op.create_table('repair_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('failure_signature', sa.Text(), server_default='', nullable=False),
    sa.Column('cause_category', sa.Text(), server_default='', nullable=False),
    sa.Column('defect_origin', sa.Text(), server_default='indetermine', nullable=False),
    sa.Column('confirmation_status', sa.Text(), server_default='not_required', nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.Text(), nullable=True),
    sa.Column('what_was_tried', sa.Text(), server_default='', nullable=False),
    sa.Column('human_verdict', sa.Text(), server_default='', nullable=False),
    sa.Column('human_origin', sa.Text(), server_default='', nullable=False),
    sa.Column('human_comment', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("confirmation_status IN ('pending_human', 'confirmed', 'rejected', 'not_required')", name='ck_repair_attempt_confirmation_status'),
    sa.CheckConstraint("defect_origin IN ('test_a_reparer', 'vrai_bug', 'indetermine')", name='ck_repair_attempt_defect_origin'),
    sa.CheckConstraint("human_origin IN ('', 'test_a_reparer', 'vrai_bug', 'indetermine')", name='ck_repair_attempt_human_origin'),
    sa.CheckConstraint("human_verdict IN ('', 'confirmed', 'overturned')", name='ck_repair_attempt_human_verdict'),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_repair_execution', 'repair_attempt', ['execution_id'], unique=False)
    op.create_table('scenario_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.Text(), nullable=False),
    sa.Column('execution_status', sa.Text(), nullable=False),
    sa.Column('functional_status', sa.Text(), nullable=False),
    sa.Column('failure_type', sa.Text(), server_default='', nullable=False),
    sa.Column('cause_category', sa.Text(), server_default='', nullable=False),
    sa.Column('error_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('step_text', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("execution_status IN ('success', 'technical_error')", name='ck_scenario_result_execution_status'),
    sa.CheckConstraint("functional_status IN ('conforme', 'non_conforme', 'indetermine', 'donnee_invalide')", name='ck_scenario_result_functional_status'),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_scenario_execution', 'scenario_result', ['execution_id'], unique=False)
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('statut_manuel', sa.Text(), server_default='', nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Text(), server_default='', nullable=False),
    sa.Column('attachments_path', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("(mode = 'automatique' AND execution_id IS NOT NULL AND statut_manuel = '') OR (mode = 'manuelle' AND execution_id IS NULL AND statut_manuel <> '')", name='ck_test_result_mode_coherence'),
    sa.CheckConstraint("mode IN ('manuelle', 'automatique')", name='ck_test_result_mode'),
    sa.CheckConstraint("statut_manuel IN ('', 'passed', 'failed', 'retest', 'blocked')", name='ck_test_result_statut_manuel'),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_result_case', 'test_result', ['case_id'], unique=False)
    op.create_index('idx_result_run_case', 'test_result', ['run_id', 'case_id'], unique=False)
    op.create_index('uq_result_execution', 'test_result', ['execution_id'], unique=True, sqlite_where=sa.text('execution_id IS NOT NULL'), postgresql_where=sa.text('execution_id IS NOT NULL'))
    op.create_table('result_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('stored_name', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), server_default='', nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['test_result.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_attachment_result', 'result_attachment', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attachment_result', table_name='result_attachment')
    op.drop_table('result_attachment')
    op.drop_index('uq_result_execution', table_name='test_result', sqlite_where=sa.text('execution_id IS NOT NULL'), postgresql_where=sa.text('execution_id IS NOT NULL'))
    op.drop_index('idx_result_run_case', table_name='test_result')
    op.drop_index('idx_result_case', table_name='test_result')
    op.drop_table('test_result')
    op.drop_index('idx_scenario_execution', table_name='scenario_result')
    op.drop_table('scenario_result')
    op.drop_index('idx_repair_execution', table_name='repair_attempt')
    op.drop_table('repair_attempt')
    op.drop_index('idx_cost_period', table_name='cost_ledger')
    op.drop_index('idx_cost_case', table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index('idx_review_version', table_name='review_decision')
    op.drop_table('review_decision')
    op.drop_index('idx_execution_run', table_name='execution')
    op.drop_index('idx_execution_case', table_name='execution')
    op.drop_table('execution')
    op.drop_index('idx_runcase_run', table_name='test_run_case')
    op.drop_table('test_run_case')
    op.drop_index('idx_version_case', table_name='test_case_version')
    op.drop_table('test_case_version')
    op.drop_table('run_case_assignment')
    op.drop_index('uq_case_group_title', table_name='test_case', sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.drop_index('uq_case_feature_slug', table_name='test_case', sqlite_where=sa.text("feature_slug != '' AND deleted_at = ''"), postgresql_where=sa.text("feature_slug != '' AND deleted_at = ''"))
    op.drop_index('idx_case_module', table_name='test_case')
    op.drop_index('idx_case_group', table_name='test_case')
    op.drop_table('test_case')
    op.drop_index('uq_group_module_title', table_name='case_group', sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.drop_index('idx_group_module', table_name='case_group')
    op.drop_index('idx_case_group_parent', table_name='case_group')
    op.drop_table('case_group')
    op.drop_index('idx_user_group_member_user', table_name='user_group_member')
    op.drop_table('user_group_member')
    op.drop_index('idx_run_project', table_name='test_run')
    op.drop_table('test_run')
    op.drop_index('idx_project_member_user', table_name='project_member')
    op.drop_table('project_member')
    op.drop_table('project_group_access')
    op.drop_index('uq_module_project_name', table_name='module', sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.drop_index('idx_module_project', table_name='module')
    op.drop_table('module')
    op.drop_table('user_group')
    op.drop_table('user')
    op.drop_table('project_access')
    op.drop_index('uq_project_name', table_name='project', sqlite_where=sa.text("deleted_at = ''"), postgresql_where=sa.text("deleted_at = ''"))
    op.drop_table('project')
    op.drop_index('idx_generation_job_status', table_name='generation_job')
    op.drop_table('generation_job')
    op.drop_table('app_setting')
    op.drop_index('idx_access_audit_project_time', table_name='access_audit')
    op.drop_table('access_audit')
    # ### end Alembic commands ###
